### PR TITLE
Add ubuntu/centos images for building.

### PR DESCRIPTION
**Pull request by Shylock-Hg**

### CODE REVIEW

**Comment by yixinglu** [comment]
close vesoft-inc/nebula#905

**Comment by yixinglu** [comment]
Hi @Shylock-Hg . We have provided a [`centos` version](https://github.com/vesoft-inc/nebula-dev-docker/blob/master/Dockerfile.centos) image for building nebula. Are you interested in updating this PR to add an `ubuntu` version dockerfile ?

**Comment by Shylock-Hg** [comment]
> Hi @Shylock-Hg . We have provided a [`centos` version](https://github.com/vesoft-inc/nebula-dev-docker/blob/master/Dockerfile.centos) image for building nebula. Are you interested in updating this PR to add an `ubuntu` version dockerfile ?

ok

**Comment by Shylock-Hg** [comment]
> Hi @Shylock-Hg . We have provided a [`centos` version](https://github.com/vesoft-inc/nebula-dev-docker/blob/master/Dockerfile.centos) image for building nebula. Are you interested in updating this PR to add an `ubuntu` version dockerfile ?

And I rename the centos Dockerfile for syntax highlight.

**Comment by yixinglu** [comment]
> > Hi @Shylock-Hg . We have provided a [`centos` version](https://github.com/vesoft-inc/nebula-dev-docker/blob/master/Dockerfile.centos) image for building nebula. Are you interested in updating this PR to add an `ubuntu` version dockerfile ?
> 
> And I rename the centos Dockerfile for syntax highlight.

We want to follow the community's common naming rules for Dockerfile, putting `Dockerfile` in front of `centos`. In addition, these dockerfile's names seem more uniform.

For `ubuntu` version docker image, we want to avoid to use rpm to install nebula dependencies. If you try to use latest gcc(or 8.3.1), installed by `apt` as possible, to build them like in centos dockerfile, it would be pretty good.

**Comment by yixinglu** [comment]
Nebula has upgraded third party dependencies installation method, so close this PR. If you are interest in new docker image building steps, please refer to PR #12 . Thanks for your contribution.

**Pull request closed without merging**
